### ISSUE TITLE
Adding a boilerplate to this kickstart

### ISSUE THREAD

**Issue by josephdburdick** [thereactivestack/kickstart-meteor-react-router#80] opened 2016-05-08 17:37 UTC
Hi there, awesome project! I've got the following implementation attempt that isn't working: https://github.com/josephdburdick/kickstart-meteor-react-router

Basically I started with a clone of this repo and tried to redirect webpack to point to the imports folder instead, as that is how things are done for [Base](https://github.com/themeteorchef/base), a React/React-Router/import-friendly Meteor 1.3 boilerplate which has a few things already figured out. 

Once I moved to webpack at work it has become very unwieldy to rely on Meteor's loader for personal projects. I am wondering what's the most straightforward way to apply an already-import-friendly boilerplate to this setup? It's already using React router, React, etc. I've spend a couple days on this, there are no errors anymore but the client just appears blank. I assume it has something to do with a router mismatch. 

Any ideas? Thanks in advance!

**Comment by eXon** [comment] 2016-05-08 19:44
I encourage you to ask for help on the Meteor forums. This is not a bug issue so I'm closing this.

**Closed by eXon** 2016-05-08 19:44 UTC
